spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    url: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
    password: ${DB_PASS}
  flyway:
    enabled: 'false'
  application:
    name: saludo
springdoc:
  api-docs:
    path: /api-docs
smtp:
  pass: clave-prueba
  user: prueba
secret: ThisIsASecretKey

servicio: ${SERVICIO}
