name: Continuos Delivery
on:
  push:
    branches: [ 'main' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Descargando el Repo
        with:
          fetch-depth: 0
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: danielsabana/cualquiercosa
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: danielsabana
          password: ${{ secrets.DOCKER_PASSWORD }}
