name: Continuos Integration
on:
  pull_request:
    branches: [ 'main','develop','release','master','xxx' ]
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Descargando el Repo
        with:
          fetch-depth: 0
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          login: sqa_4a4ae29e1505776d1b336ef2d3ec71f6076bdac6
          host: http://217.76.49.138:9000
